ErinBecker/instructor-training-reorg

- _episodes/02-practice.md
- _episodes/05-memory.md
- _episodes/08-motivation.md
- _episodes/09-mindset.md
- _episodes/11-performance.md
- _episodes/13-second-welcome.md
- _episodes/15-live.md
- _episodes/20-practices.md
- Add YAML headers for new episodes
- Check and fix timings for episodes
- Remove materials voted by Trainers as unneeded
- Parsons problems
- Battling theories
- Concept inventories
- Why not a MOOC
> format episodes and remove materials

- setup.md
This is my proposed implementation of Issue #484 from swcarpentry/instructor-training (trying to create a PR there redirected me here). Each member of my group successfully used CaptureCast during our instructor training. To give credit where credit is due, I initially learned about CaptureCast here: http://www.freetech4teachers.com/2016/04/capturecast-record-screencasts-on-your.html
> Add CaptureCast suggestion to instructor setup

- _episodes/01-welcome.md
- _episodes/02-practice.md
- _episodes/11-performance.md
- _episodes/14-learning-objectives.md
- _episodes/15-live.md
- _episodes/20-practices.md
- _episodes/22-carpentries.md
This PR changes discussion boxes to challenges as appropriate. Also revises key points and learning objectives for the first lesson.
> Format challenges and revise key points

- _episodes/04-expertise.md
- _episodes/08-motivation.md
Fixes https://github.com/ErinBecker/instructor-training-reorg/issues/10
> exercise on motivational language

- _episodes/02-practice.md
- _episodes/04-expertise.md
This PR includes a rewrite of the section on how formative assessments work to help diagnose and correct misconceptions.
> Rewrite formative assessment section

- _episodes/04-expertise.md
This PR starts re-working the expertise section.
> revamp expertise section

- README.md
also moved a name to keep all in alphabetical order
> added Jason's name to README list

- _extras/guide.md
I have incorporated some of mine and @gvwilson's tips as per @anelda's request. 
Likely there are other tips that could be added...
> added online training tips

- _episodes/02-practice.md
- _episodes/04-expertise.md
- _episodes/05-memory.md
- _episodes/08-motivation.md
- _episodes/09-mindset.md
- _episodes/11-performance.md
- _episodes/14-learning-objectives.md
- _episodes/15-live.md
- _episodes/17-performance.md
- _episodes/20-practices.md
- _episodes/22-carpentries.md
The episodes have been organized around four themes into modules. This renames the episodes to make that organization explicit.
> name modules

- _episodes/08-motivation.md
I propose a brief callout re-emphasizing that learner confusion needs to be addressed while still recognizing that we may not catch every case.
> A Corollary Regarding Novices

- _episodes/04-expertise.md
This fixes a minor text issue in 04-expertise.
> Fix text in exercise in 04-expertise

- _episodes/09-mindset.md
Partially addresses https://github.com/ErinBecker/instructor-training-reorg/issues/45
"Add discussion of different types of praise (performance, effort, improvement) and their impacts on learners."
> Add section on praise talk

- _episodes/05-memory.md
I moved the Concept Maps section from episode 4 to episode 5.
---
> Concept Maps section

- _episodes/02-practice.md
Added a new section on our pedagogy as listed in issue #43 
Hopefully this got at the point Erin wanted to be making here.
> added carpentries pedagogical model

- _episodes/05-memory.md
I am moving the Seven Plus or Minus Two section from episode 4 to 5. I will put in another PR for deleting this section from episode 4 too.
---
> Move Seven Plus or Minus Two

- _episodes/08-motivation.md
I fixed several typos and added a solution for a challenge.
> updated episode 8: motivation

- _episodes/13-second-welcome.md
Sorry for delay. Hopefully this sums day1 and day2!
> episode 13 content

- _episodes/04-expertise.md
This objective was moved over to episode 5, so I am deleting it from episode 4.
---
> Deleted objective

- _episodes/05-memory.md
The content for this objective was moved from episode 4 to 5, so I moved this objective as well.
---
> Moved objective from episode 4 to 5

- _episodes/04-expertise.md
The content this question pertains to was moved to episode 5, so I also moved this question to there. This question can now be deleted from episode 4.
---
> Deleted question after moving it

- _episodes/09-mindset.md
Addresses 
- Expand introduction about growth vs fixed mindset to include:
- Discussion of how people with growth vs fixed mindset differ in their actions/attitudes.
- Link to Dweck's mindset self-assessment
- Discussion of performance- vs mastery/learning orientation.
from https://github.com/ErinBecker/instructor-training-reorg/issues/45
I decided to introduce the ideas behind performance and mastery/learning orientation without introducing the terminology. Thoughts? @karenword @raynamharris @smcclatchy @amyehodge
> Add intro to mindset

- _episodes/22-introductions.md
I think we have time for this in the afternoon?  Could be shortened or moved elsewhere.  Let me know.  
I do *really* like finishing with this, because it feels like a good, practical exercise to send people out the door.
> introduction material

- _episodes/02-practice.md
- _episodes/04-expertise.md
Trying to restructure around expert blind spot, addressing items in #45.
> reorganizing the expertise episode

- _episodes/05-memory.md
> starting to tackle changes in memory episode

- _episodes/01-welcome.md
- Added objective
- Added key point
- Rearranged introductions, information for trainers, information for learners, first activity
- Updated teaching experience options
- Added subheadings to workshop overview and revised /reorganized wording in each subsection
> Addressed issues 96, 48, and 56

- _episodes/17-performance.md
Hello!
I’m new and was planning to attend an SC/DC workshop soon. Hopefully this little contribution to the BBQ is worth ticking off the 1st task in #45 under `17`.
Cheers!
> episode 17: swap video for live coding

- _episodes/05-memory.md
@ErinBecker Removed the words "just demonstrated" per this issue: https://github.com/ErinBecker/instructor-training-reorg/issues/59
> Removed "just demonstrated"

- _episodes/08-motivation.md
I did my best to refer to established practices where possible
> updated with positive learning environment notes

- _episodes/08-motivation.md
It looks like a couple words were left off the end of this sentence.
> Word left off of end of sentence

- _episodes/08-motivation.md
Establish is used three times in the last two sentences. It is not needed here.
> Delete established here

- _episodes/11-performance.md
- _episodes/14-learning-objectives.md
- _episodes/22-carpentries.md
> Minor formatting fixes

- _episodes/14-learning-objectives.md
Switched order so reverse instructional design immediately succeeds **Writing Lessons** section. Revised introduction to **Learner Profiles** accordingly.
>  lesson-14 Move reverse instructional design to start of episode

- _episodes/08-motivation.md
This sentence seemed a bit unwieldy as one sentence, so I broke it up into two sentences.
> Cleared up sentence.

- _episodes/08-motivation.md
This sentence seemed awkward, so I rewrote it. Hopefully, I improved it.
> Awkward sentence

- _episodes/08-motivation.md
> A comma is not needed here.

- _episodes/08-motivation.md
The word here should be two not to.
> Should be two not to

- _episodes/08-motivation.md
This is not a question, so a period should be used.
> Question mark is not needed here

- _extras/guide.md
Makes the order a bit more (chrono)logical
> Small change in order of demo checklist

- _episodes/22-carpentries.md
Addressing #26 just removed the suggestion of doing this activity at the start of the lesson, only towards the end.
> adjust op guide activity

- _episodes/22-carpentries.md
recreating #102 which addresses #46
> raynas carpentries changes

- _episodes/15-live.md
Addresses https://github.com/swcarpentry/instructor-training/issues/471
> Specify live-coding exercise not as authentic

- _extras/guide.md
removed from lesson text in PR #133 .
> adding notes to instructors guide

- _extras/icebreakers.md
I used these two icebreakers together in class. On day 2, I had the learners at each sight go around the room and say
1. their name
2. their favorite food
3. one teaching thing they are passionate about
> icebreaker suggestions

- _episodes/14-learning-objectives.md
Addreesses https://github.com/ErinBecker/instructor-training-reorg/pull/106#issuecomment-320175964
> Add reference to another Bloom's taxonomy image

- _episodes/22-carpentries.md
> Issue459-Practice-with-infrastructure-need-to-include-DC-and-SWC

- _episodes/01-welcome.md
I found the table a bit difficult to read as previously formatted, so I changed the style to include sublists.
> Updated formating for table on Welcome page

- _episodes/05-memory.md
see https://github.com/ErinBecker/instructor-training-reorg/issues/58
> add first name

- _extras/exercises.md
Adds a small exercise at the beginning of Extras that reinforces teaching as a skill and frames it within novice/practitioner/expert
> Add teaching as a skill to Extra Exercises

- _episodes/14-lesson-study.md
This is a suggestion to retain some of the learning objectives material, but focuses that content more specifically in a way that instructors can use when preparing to teach a lesson as opposed to designing one. Also modifies some language re challenge question design to address redundancy with existing material and to encourage instructors to engage in design even where challenges are already present.
> Adding learning objectives in new form

- _episodes/08-motivation.md
Adds exercise for trainees to look at posters about accessibility and put one thing they learned in the Etherpad. (Note that there are translations available in several languages.)
> add exercise for accessibility

- _extras/figures.md
Fixes https://github.com/ErinBecker/instructor-training-reorg/issues/40
> figures.md

- _extras/glossary.md
Written for http://third-bit.com/teaching/ and now folding back in.
> Adding a glossary of terms

- _extras/glossary.md
This PR updates the glossary extra contributed by @gvwilson with terms that are used in the new version of these materials.
> Update glossary with new terms

- _episodes/09-mindset.md
Fix https://github.com/ErinBecker/instructor-training-reorg/issues/129
> add internal link

- _episodes/02-practice-learning.md
- _episodes/03-expertise.md
- _episodes/05-memory.md
- _episodes/08-motivation.md
- _episodes/09-mindset.md
- _episodes/11-practice-teaching.md
- _episodes/14-lesson-study.md
- _episodes/19-introductions.md
- _episodes/20-carpentries.md
- _episodes/22-practices.md
- _episodes/23-checkout.md
This PR goes through each episode and makes minor changes/corrections. Types of corrections include:
- Updating links to be correct episode numbering.
- Converting "student" to "learner" for consistency".
- Converting he/she to gender neutral "they" for consistent voice.
- Removing colloquialisms and slang.
- Minor format corrections.
> readthrough of all episodes
